### PR TITLE
Merge stuff from what I have in launchpad branch

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
Please, don't delete icons... they are optimized for each size (you can't use only one big svg icon for all icons sizes!). And I waste a lot of time to re-make them :(
There are some changes in the debian packaging too.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
It seems debian package is broken, after all changes. I'll see this later.

**Comment by sergiobenrocha2** [comment]
I'm getting 

```
-- Installing: /home/sergio/Projects/VBA-M/vbam-emperor_fork-git-sergio/debian/tmp/usr/share/icons/hicolor/scalable/apps/vbam.svg/vbam.svg
CMake Error at src/gtk/cmake_install.cmake:36 (FILE):
  file INSTALL cannot find
  "/home/sergio/Projects/VBA-M/vbam-emperor_fork-git-sergio/builddir/src/gtk/gvbam".
Call Stack (most recent call first):
  cmake_install.cmake:61 (INCLUDE)


make[1]: *** [install] Error 1
```

3 errors:
first, you have an weird apps/vbam.svg/vbam.svg path, the vbam.svg is inside usr/share/icons/hicolor/scalable/apps/
second, it's missing the others png icons (16x16/apps/vbam.png, 32x32...)
third, make command from rules are trying to get gvbam from the wrong place, it seems now it appears in builddir/, instead of builddir/src/gtk/

**Comment by sergiobenrocha2** [comment]
About the icons, take a look why you can't resize one icon to other size:

http://www.zimagez.com/galerie/Same-size--but-one-weird-32609-0.php

- the first icon is the 48 px I think, resized to 128
- and the second, is the 128 optimized icon

**Comment by EmperorArthur** [comment]
Manually fixed the icon issue in master.
I've also gone ahead and added a script to regenerate all the icons from the svg files in src.

**Comment by EmperorArthur** [comment]
I've cherry-picked all the non icon commits.
Thanks for the help.

**Comment by sergiobenrocha2** [comment]
why the icons have the 128x128.png name, for example? (in hicolor/128x128/apps/)

They should call vbam.png

**Comment by EmperorArthur** [comment]
Scripting error, and proof of why I should double check things when coding at 4am.  Fixed.

**Pull request closed without merging**
